In [2]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [3]:
tf.__version__

'2.15.0'

In [3]:
dataset = pd.read_csv('Data.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [6]:
#Label Encoding the Gender column
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [7]:
#One Hot Encoding the Geography column
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder = 'passthrough')
X = np.array(ct.fit_transform(X))
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [8]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [9]:
print(X_train)

[[0.0 0.0 1.0 ... 1 0 163830.64]
 [0.0 1.0 0.0 ... 1 1 57098.0]
 [1.0 0.0 0.0 ... 1 0 185630.76]
 ...
 [1.0 0.0 0.0 ... 1 0 181429.87]
 [0.0 0.0 1.0 ... 1 1 148750.16]
 [0.0 1.0 0.0 ... 1 0 118855.26]]


In [10]:
print(y_train)

[0 0 0 ... 0 0 1]


In [11]:
print(X_test)

[[0.0 1.0 0.0 ... 1 1 192852.67]
 [1.0 0.0 0.0 ... 1 0 128702.1]
 [0.0 0.0 1.0 ... 1 1 75732.25]
 ...
 [0.0 0.0 1.0 ... 1 0 141533.19]
 [0.0 1.0 0.0 ... 1 1 11276.48]
 [0.0 1.0 0.0 ... 1 0 192950.6]]


In [12]:
print(y_test)

[0 1 0 ... 0 0 0]


In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [14]:
print(X_train)

[[-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   1.10643166]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -0.74866447]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.48533467]
 ...
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   1.41231994]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
   0.84432121]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   0.32472465]]


In [15]:
print(X_test)

[[-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
   1.61085707]
 [ 0.98560362 -0.5698444  -0.57369368 ...  0.64259497 -1.03227043
   0.49587037]
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497  0.9687384
  -0.42478674]
 ...
 [-1.01460667 -0.5698444   1.74309049 ...  0.64259497 -1.03227043
   0.71888467]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497  0.9687384
  -1.54507805]
 [-1.01460667  1.75486502 -0.57369368 ...  0.64259497 -1.03227043
   1.61255917]]


In [17]:
#Building the ANN
ann = tf.keras.models.Sequential()
#First and second hidden layer
ann.add(tf.keras.layers.Dense(units = '6', activation = 'relu'))
ann.add(tf.keras.layers.Dense(units = '6', activation = 'relu'))
#Output layer
ann.add(tf.keras.layers.Dense(units='1', activation = 'sigmoid'))

In [19]:
#Compiling the ANN
ann.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [20]:
#Training the ANN
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100


250/250 [==============================] - 2s 1ms/step - loss: 0.4995 - accuracy: 0.7968
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4566 - accuracy: 0.7971
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4411 - accuracy: 0.8036
Epoch 4/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4337 - accuracy: 0.8080
Epoch 5/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4292 - accuracy: 0.8109
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4256 - accuracy: 0.8139
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4223 - accuracy: 0.8170
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4195 - accuracy: 0.8186
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4168 - accuracy: 0.8226
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4146 - accu

250/250 [==============================] - 0s 1ms/step - loss: 0.3904 - accuracy: 0.8367
Epoch 78/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3902 - accuracy: 0.8367
Epoch 79/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3900 - accuracy: 0.8365
Epoch 80/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3904 - accuracy: 0.8376
Epoch 81/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3899 - accuracy: 0.8363
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3904 - accuracy: 0.8371
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3901 - accuracy: 0.8375
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3903 - accuracy: 0.8366
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3900 - accuracy: 0.8359
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3898 - accuracy: 

In [21]:
#Predicting the ANN model
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))

1/1 [==============================] - 0s 110ms/step
[[0.11965872]]


In [22]:
print(ann.predict(sc.transform([[1, 0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])) > 0.5)

1/1 [==============================] - 0s 22ms/step
[[False]]


In [25]:
#Predicitng the test set results
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred), 1), y_test.reshape(len(y_test), 1)), 1))

63/63 [==============================] - 0s 1ms/step
[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [26]:
#Making the confusion matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1538   57]
 [ 256  149]]


0.8435